### PR TITLE
Use SIPickle instead of SpikeGLX

### PR DESCRIPTION
**Pull request by alejoe91**
Demonstration of `SIPickleRecording`. 

Needs this branch of `nwb-conversion-tools`: https://github.com/catalystneuro/nwb-conversion-tools/pull/72

### CODE REVIEW

**Comment by bendichter** [comment]
@alejoe91 I understand that on the processed side this will allow us to write other types of data like waveforms and metrics, but what's the advantage of a Pickle interface for recordings? Why wouldn't we just use SpikeGLX's format?

**Comment by alejoe91** [comment]
@bendichter Synchronization! In the ephys pipeline we want to synchronize the recording with TTLs so that sorted data are also synched. Then a simple `dump_to_pickle` of the `SubRecordingExtractor` would allow the converter to re-apply the same changes. Another use case could be removing noisy channels! This could be done via visual inspection and another `SubRecordingExtractor`, or even automatically using the `spiketoolkit.preprocessing.remove_bad_channels`

**Comment by bendichter** [comment]
@alejoe91 For synchronization we can use a `SubRecordingExtractor`, and I don't want to remove noisy channels in the raw data.

**Comment by CodyCBakerPhD** [comment]
@bendichter @alejoe91 Check out https://github.com/catalystneuro/nwb-conversion-tools/pull/74 for the SubRecordingExtractor version for allowing synchronization

**Comment by bendichter** [comment]
@alejoe91 what do you think of using Cody's solution instead of the Pickle solution. It should mean 1 fewer read and write if I understand correctly

**Comment by alejoe91** [comment]
> @alejoe91 what do you think of using Cody's solution instead of the Pickle solution. It should mean 1 fewer read and write if I understand correctly

If we always need to trim the recording using the first TTL Cody's solution is probably better in this case. The pickle could still be handy in other situations. Let's go for Cody's solution here

**Pull request closed without merging**
